name: Chech Markdown

on:
    push:

jobs:
    markdown-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Check README.md
              uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24
              with:
                config: 'config/custom.markdownlint.jsonc'
                globs: README.md
