name: Chech Markdown

on:
    push:

jobs:
    markdown-lint:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Check README.md
              uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
              with:
                config: 'config/custom.markdownlint.jsonc'
                globs: README.md

    notify-on-failure:
        needs: [markdown-lint]
        if: failure()
        uses: ./.github/workflows/notify-slack-on-failure.yml
        secrets:
            slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
            slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
