name: GitHub-Profile-Summary-Cards

on:
    schedule:
        - cron: "0 0 * * 0" # 毎週日曜日の午前0時(UTC)に実行
    workflow_dispatch: # 手動実行も可能

jobs:
    build:
        runs-on: ubuntu-latest
        name: Generate GitHub Cards
        permissions:
            contents: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  token: ${{ secrets.PROFILE_SUMMARY_TOKEN }}

            - name: Generate Profile Summary Cards
              uses: vn7n24fzkq/github-profile-summary-cards@974577f1823715ca047e9976548634816a3a0264 # release
              env:
                  GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_TOKEN }}
              with:
                  USERNAME: ${{ github.repository_owner }}
